project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_url_env: CROWDIN_BASE_URL
base_path: .
preserve_hierarchy: true
files:
    - source: /src/locales/en/messages.po
      dest: /icons/**/%original_file_name%
      translation: /src/locales/%two_letters_code%/messages.po
