
import type { LinguiConfig } from '@lingui/conf';

// This file is auto generated by the i18n script
const config: LinguiConfig = {
  locales: ['en', 'nb', 'fi', 'da', 'sv'],
  sourceLocale: 'en',
  catalogs: [
  {
    include: ['scripts/temp/icon-translations.js'],
    path: 'src/locales/{locale}/messages',
  },
],
  compileNamespace: 'es',
};

export default config;